### ISSUE TITLE
Dual License Apache/MIT

### ISSUE THREAD

**Issue by ValorZard** [ValorZard/Quad-Fighter-2#3]
I want to do this to be compliant with the larger rust ecosystem, but first I think i need permission from the two people that have already contributed to this project. @OptimisticPeach and @gschup could you give permission for me?

**Comment by gschup** [comment]
I don't mind at all. GGRS is MIT as well, so go ahead!

**Comment by OptimisticPeach** [comment]
Oh, yeah. I give permission for my previous and future contributions to Quad-Fighter-2 to be relicensed under MIT or Apache 2.0 at the user's discretion.
